import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Container from '../components/common/Container'
import Header from '../components/common/Header'
import Photo from '../components/photo/Photo'
import Upload from '../components/photo/Upload'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <Upload />
      </Container>
      <div className="py-6 px-4 bg-slate-50 border-t border-t-gray-300">
        <h5 className="text-2xl tracking-tigh font-bold">Your photos</h5>
        <div className="mt-8 flex flex-wrap justify-center">
          {Array<undefined>(10).fill(undefined).map((_, i) => <Photo key={i} />)}
        </div>
      </div>
    </>
  )
}

export default Home
